# ESP32-S3-Box-3 Robbie Direct Voice - Minimal Test
# No wake word for now - testing custom component only

substitutions:
  name: "esp32-s3box-3"
  friendly_name: "ESP32 S3 Box 3"
  robbie_vps_host: "robbie.openclaw.hodges.nl"
  robbie_vps_port: "8081"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source:
      type: local
      path: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome

logger:
  level: DEBUG

i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO45
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO2

microphone:
  - platform: i2s_audio
    id: box_mic
    i2s_audio_id: i2s_shared
    i2s_din_pin: GPIO16
    adc_type: external
    pdm: false
    bits_per_sample: 16bit
    channel: left

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_audio_id: i2s_shared
    i2s_dout_pin: GPIO15
    dac_type: external

# Robbie Voice Component
robbie_voice:
  id: robbie
  microphone: box_mic
  vps_host: ${robbie_vps_host}
  vps_port: ${robbie_vps_port}

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

button:
  - platform: template
    name: "Test Robbie Voice"
    on_press:
      - robbie_voice.start:
          id: robbie
