# ESP32-S3-Box-3 - Sensors Only (minimal)
# No voice, no wake word, just sensors

substitutions:
  name: "esp32-s3box-3"
  friendly_name: "ESP32 S3 Box 3"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO

# Basic sensors
sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: internal_temperature
    name: "Internal Temperature"

binary_sensor:
  - platform: status
    name: "Status"

button:
  - platform: restart
    name: "Restart"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "MAC Address"
